const fs = require("node:fs"), vm = require("node:vm"), assert = require("node:assert/strict");
const { plan, saved, diagnostic } = JSON.parse(fs.readFileSync(0, "utf8"));
const source = fs.readFileSync(require("node:path").join(__dirname, "../docs/refresher.js"), "utf8");
const page = fs.readFileSync(require("node:path").join(__dirname, "../docs/index.html"), "utf8");
const timestamps = page.slice(page.indexOf("function localDay("), page.indexOf("function sessionInstant("));
const practice = fs.readFileSync(require("node:path").join(__dirname, "../docs/practice.js"), "utf8");
const sandbox = { diagnostic, DATA: { refresher: plan }, P: { xp: 50, solved: { "1.2": {} }, refresher: saved }, nowIso: () => "2026-09-05T12:00:00.000Z", saveProgress: () => true, toast: () => {}, assert };
vm.createContext(sandbox);
vm.runInContext(timestamps + practice + source + `
  assert.equal(refresherState().next_activity, "baseline-plan");
  assert.equal(refresherStatus(refresherState(), "baseline-review"), "skipped");
  const before = JSON.stringify(P);
  refresherState();
  assert.equal(JSON.stringify(P), before);
  saveRefresher(updateRefresher(P.refresher, "revisit", "baseline-diagnostic"));
  saveRefresher(updateRefresher(P.refresher, "note", "baseline-diagnostic", "A saved takeaway"));
  assert.equal(P.xp, 50);
  assert.deepEqual(Object.keys(P.solved), ["1.2"]);
  assert.equal(refresherState().next_activity, "baseline-diagnostic");
  const held = JSON.stringify(P);
  saveProgress = () => false;
  assert.equal(saveRefresher(updateRefresher(P.refresher, "done")), false);
  assert.equal(JSON.stringify(P), held);
  assert.equal(saveRefresher(updateRefresher(P.refresher, "open", "mocks-a"), {id:"mock-pending"}), false);
  assert.equal(JSON.stringify(P), held); // failed storage cannot orphan an active mock
  saveProgress = () => { assert.equal(P.interview.id, P.refresher.mock_sessions["mocks-a"]); return true; };
  const linked = updateRefresher(P.refresher, "open", "mocks-a");
  linked.mock_sessions["mocks-a"] = "mock-saved";
  assert.equal(saveRefresher(linked, {id:"mock-saved"}), true);
  saveProgress = () => true;
  saveRefresher(updateRefresher(P.refresher, "open", "baseline-diagnostic"));
  assert.throws(() => refresherState({version:true}), /not supported/);
  diagnostic.attempts = [{exercise_id:"1.3",passed:false,at:diagnostic.started}];
  diagnostic.reflections = {"1.2":{confidence:"needs_review",mistake_note:"forgot strip"}};
  const rows = refresherWeakAreas(diagnostic);
  assert.equal(rows.map(row => row.id).join(","), "1.2,1.3");
  diagnostic.reflections = {};
  diagnostic.attempts = [{exercise_id:"1.2",passed:true,at:diagnostic.started},{exercise_id:"1.2",passed:false,at:diagnostic.started}];
  assert.equal(refresherWeakAreas(diagnostic)[0].reasons[0], "Latest diagnostic run did not pass");
  diagnostic.attempts.push({exercise_id:"1.2",passed:true,at:diagnostic.started});
  assert.equal(refresherWeakAreas(diagnostic).length, 0);
  diagnostic.attempts.push({exercise_id:"1.3",passed:false,at:"invalid"});
  assert.equal(refresherWeakAreas(diagnostic).length, 0);
  assert.equal(refresherWeakAreas({attempts:[],reflections:{"1.2":{confidence:"needs_review"}}}).length, 0);
`, sandbox);
process.stdout.write(JSON.stringify(sandbox.P.refresher));
