// Execute the shipped browser state functions, including the diagnostic hook.
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const root = path.join(__dirname, '..');
const incoming = JSON.parse(fs.readFileSync(0, 'utf8'));
const bundle = {window: {}};
vm.runInNewContext(fs.readFileSync(path.join(root, 'docs/exercises.js'), 'utf8'), bundle);
const DATA = bundle.window.COURSE_DATA;
const ALL = DATA.parts.flatMap(part => part.exercises.map(ex => ({...ex, part})));
const BY_ID = Object.fromEntries(ALL.map(ex => [ex.id, ex]));
const page = fs.readFileSync(path.join(root, 'docs/index.html'), 'utf8');
const start = page.indexOf('function localDay('), end = page.indexOf('// ------------------------------------------------------------------ rendering helpers', start);
const memory = new Map();
const storage = {fail: false, getItem: key => memory.get(key) ?? null, setItem(key, value) {if (this.fail) throw Error('full'); memory.set(key, value);}};
const code = page.slice(start, end) + '\n' + fs.readFileSync(path.join(root, 'docs/practice.js'), 'utf8') + '\n' + fs.readFileSync(path.join(root, 'docs/review.js'), 'utf8');
const output = vm.runInNewContext(code + `
 const now = new Date('2026-03-07T12:00:00');
 let queue = reflectReviewQueue(null, '1.1', 'confident', 'bounds', null, 'exercise', now);
 assert.equal(queue.items['1.1'].next_review, '2026-03-10');
 queue = reflectReviewQueue(queue, '1.2', 'needs_review', 'empty input', null, 'exercise', now);
 queue = reflectReviewQueue(queue, '1.3', 'needs_review', 'week', 7, 'exercise', now);
 queue = reflectReviewQueue(queue, '1.4', 'confident', 'month', 30, 'exercise', now);
 assert.equal(queue.items['1.2'].next_review, '2026-03-08');
 assert.equal(queue.items['1.3'].next_review, '2026-03-14');
 assert.equal(queue.items['1.4'].next_review, '2026-04-06');
 assert.equal(reviewQueueRows(queue, '2026-03-11', true).map(row=>row.id).join(','), '1.2,1.1');
 assert.equal(reviewQueueRows(queue, '2026-03-07').length, 4);
 for (const invalid of [true, 0, 2, '7', 31]) assert.throws(()=>reflectReviewQueue(queue,'1.1','confident','',invalid));
 assert.throws(()=>reflectReviewQueue(queue,'1.1\\n','confident',''));
 for (const invalid of ['2026-02-30','0000-01-01','2026-3-7','2026-03-07\\n',null]) {
   const bad = practiceClone(queue); bad.items['1.1'].next_review=invalid; assert.throws(()=>reviewQueue(bad));
 }
 P={...blankProgress(),xp:71,solved:{'1.1':{xp:9}},hints:{'1.1':2},review_queue:incoming};
 const lifetime=JSON.stringify({xp:P.xp,solved:P.solved,hints:P.hints,attempts:P.attempts});
 const diagnostic=beginDiagnostic();
 updateDiagnostic('1.3','reflect',diagnostic.id,{confidence:'needs_review',note:'diagnostic'});
 assert.equal(P.review_queue.items['1.3'].sources.join(','),'diagnostic');
 saveExerciseReflection('1.3','confident','ordinary',30);
 assert.equal(P.review_queue.items['1.3'].sources.join(','),'diagnostic,exercise');
 assert.equal(Object.keys(P.review_queue.items).filter(id=>id==='1.3').length,1);
 updateDiagnostic('1.3','reflect',diagnostic.id,{confidence:'confident',note:'current diagnostic confidence'});
 P.review_queue.items['1.3'].next_review='2026-12-01';saveProgress();
 updateDiagnostic('1.3','reflect',diagnostic.id,{confidence:'confident',note:'note-only change'});
 assert.equal(P.review_queue.items['1.3'].interval_days,30);assert.equal(P.review_queue.items['1.3'].next_review,'2026-12-01');
 let before=JSON.stringify(P), disk=memory.get(STORE_KEY); storage.fail=true;
 assert.throws(()=>updateDiagnostic('1.3','reflect',diagnostic.id,{confidence:'needs_review',note:'must not persist'}));
 assert.equal(JSON.stringify(P),before); assert.equal(memory.get(STORE_KEY),disk); storage.fail=false;
 memory.set('ordinary-answer:1.1','keep saved answer');
 const first=beginReview(['1.1']);
 updateReview('1.1','draft',first.id,{code:'my review draft'});
 updateReview('1.1','attempt',first.id,{passed:true});
 updateReview('1.1','attempt',first.id,{passed:false});
 updateReview('1.1','help',first.id);
 assert.equal(practiceSummary(P.review_session)[0].outcome,'not_passed');
 assert.equal(beginReview(['1.2']).id,first.id);
 saveProgress(); P=loadProgress(); assert.equal(reviewSession().drafts['1.1'],'my review draft');
 updateReview('1.1','reflect',first.id,{confidence:'needs_review',note:'review',interval:7});
 assert.equal(P.review_queue.items['1.1'].interval_days,7);
 saveProgress();P=loadProgress();assert.equal(reviewSession().reflections['1.1'].interval_days,7);
 updateReview('1.1','reflect',first.id,{confidence:'needs_review',note:'edited note'});
 assert.equal(P.review_queue.items['1.1'].interval_days,7);
 before=JSON.stringify(P);storage.fail=true;assert.throws(()=>beginReview(['1.1'],true));assert.equal(JSON.stringify(P),before);storage.fail=false;
 const second=beginReview(['1.1'],true);
 assert.notEqual(second.id,first.id);assert.equal(Object.keys(second.drafts).length,0);assert.equal(second.attempts.length,0);
 assert.equal(P.review_history[0].drafts['1.1'],'my review draft');
 before=JSON.stringify(P);assert.throws(()=>updateReview('1.1','attempt',first.id,{passed:true}));assert.equal(JSON.stringify(P),before);
 assert.equal(memory.get('ordinary-answer:1.1'),'keep saved answer');
 assert.equal(JSON.stringify({xp:P.xp,solved:P.solved,hints:P.hints,attempts:P.attempts}),lifetime);
 finishReview();assert.equal(reviewSession(),null);assert.equal(P.review_history.length,2);
 saveProgress();P=loadProgress();assert.equal(P.review_queue.items['1.2'].mistake_note,'cross-client note');
 JSON.stringify(P.review_queue);
`, {assert, DATA, ALL, BY_ID, incoming, Date, window: {}, localStorage: storage, memory, storage, STORE_KEY: 'review-test', LEGACY_INTERVIEW_KEY: 'legacy-round'});
process.stdout.write(output);
