// Evaluate the shipped browser code against its frozen mapping and an edited layout.
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const vm = require('node:vm');
const incoming = JSON.parse(fs.readFileSync(0, 'utf8'));
const bundle = {window:{}};
vm.runInNewContext(fs.readFileSync(path.join(__dirname, '../docs/exercises.js'), 'utf8'), bundle);
const DATA = bundle.window.COURSE_DATA;
const oldKey = '1.1:2', cardId = DATA.legacy_card_ids[oldKey];
const lesson = DATA.parts[0].lessons[0];
const original = lesson.cards.find(card => card.id === cardId);
lesson.cards.splice(lesson.cards.indexOf(original), 1);
lesson.cards.unshift({id:'new-inserted-card',kind:'quiz'});
lesson.cards.push(original);
const page = fs.readFileSync(path.join(__dirname, '../docs/index.html'), 'utf8');
const start = page.indexOf('function localDay(');
const end = page.indexOf('// ------------------------------------------------------------------ rendering helpers', start);
const values = new Map();
const storage = {fail:false,getItem:key=>values.get(key) ?? null,setItem(key,value){if(this.fail) throw Error('full');values.set(key,value);}};
const output = vm.runInNewContext(page.slice(start,end) + `
 const oldState={done:true,correct:true,tries:1};
 localStorage.setItem(STORE_KEY, JSON.stringify({xp:71,cards:{[oldKey]:oldState,'99.1:9':{note:'keep'}},card_reward_history:{[oldKey]:true}}));
 P=loadProgress();
 assert.equal(LESSONS[0].cards.at(-1).id,cardId);
 assert.equal(cardState('1.1',cardId).correct,true);
 assert.equal(cardState('1.1','new-inserted-card').done,false);
 assert.equal(cardState('2.1',cardId).correct,true);
 assert.equal(P.cards['99.1:9'].note,'keep');
 assert.equal(recordCard('1.1',cardId,true,true),0);
 assert.equal(recordCard('1.1','new-inserted-card',true,true),1);
 cardRewardHistory(); delete P.cards[cardId]; saveProgress(); P=loadProgress();
 assert.equal(cardState('1.1',cardId).done,false);
 assert.equal(P.cards[oldKey].done,true);
 assert.equal(recordCard('1.1',cardId,true,true),0);
 assert.equal(P.xp,72);
 const oldDraft=DRAFT_KEY+'card:'+oldKey, newDraft=DRAFT_KEY+'card:'+cardId;
 localStorage.setItem(oldDraft,'legacy draft');
 assert.equal(readCardDraft('new-inserted-card'),null);
 assert.equal(readCardDraft(cardId),'legacy draft');
 assert.equal(localStorage.getItem(newDraft),'legacy draft');
 assert.equal(localStorage.getItem(oldDraft),'legacy draft');
 localStorage.setItem(newDraft,'current draft');
 assert.equal(readCardDraft(cardId),'current draft');
 assert.equal(localStorage.getItem(oldDraft),'legacy draft');
 values.delete(newDraft); storage.fail=true;
 assert.equal(readCardDraft(cardId),'legacy draft');
 assert.equal(localStorage.getItem(oldDraft),'legacy draft');
 storage.fail=false;
 const conflict=migrateCardProgress({cards:{[oldKey]:oldState,[cardId]:{done:false,tries:2,correct:false}},card_reward_history:{[oldKey]:true,[cardId]:false}});
 assert.equal(conflict.cards[cardId].done,false);
 assert.equal(conflict.cards[oldKey].done,true);
 assert.equal(conflict.card_reward_history[cardId],false);
 P=migrateCardProgress(Object.assign(blankProgress(),{xp:71,cards:{[oldKey]:oldState,[cardId]:{done:false,tries:0,correct:null}}}));
 assert.equal(cardState('1.1',cardId).done,false);
 assert.equal(P.card_reward_history[cardId],true);
 assert.equal(recordCard('1.1',cardId,true,true),0);
 assert.equal(P.xp,71);
 // A CLI-migrated import still supports draft migration from this browser.
 P=migrateCardProgress(Object.assign(blankProgress(),incoming));
 assert.equal(recordCard('1.1',cardId,true,true),0);
 assert.equal(readCardDraft(cardId),'legacy draft');
 saveProgress(); P=loadProgress();
 JSON.stringify(P);
`, {assert,DATA,Date,localStorage:storage,storage,values,oldKey,cardId,incoming,ALL:[],BY_ID:{},STORE_KEY:'test-card-ids',DRAFT_KEY:'test-draft:'});
process.stdout.write(output);
