#!/usr/bin/env python3
"""Bundle the curriculum into docs/exercises.js for the browser version.

Usage:
  python tools/build_web.py           # (re)generate docs/exercises.js
  python tools/build_web.py --check   # exit 1 if docs/exercises.js is stale
"""
from __future__ import annotations

import base64
import datetime as dt
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

from course import __version__  # noqa: E402
from course.catalog import KYU_XP, load_catalog, total_xp  # noqa: E402
from course.progress import BADGES, RANKS  # noqa: E402
from course.lessons import CARD_XP, load_lessons, validate_card_ids  # noqa: E402

from course.card_ids import LEGACY_LAYOUT, LEGACY_CARD_IDS

OUT = ROOT / "docs" / "exercises.js"
HARNESS = ROOT / "course" / "harness.py"


def read_fixtures(ex_dir: Path) -> dict:
    fixtures = {}
    fdir = ex_dir / "fixtures"
    if not fdir.is_dir():
        return fixtures
    for f in sorted(fdir.rglob("*")):
        if not f.is_file():
            continue
        rel = f.relative_to(ex_dir).as_posix()
        raw = f.read_bytes()
        try:
            fixtures[rel] = {"text": raw.decode("utf-8")}
        except UnicodeDecodeError:
            fixtures[rel] = {"base64": base64.b64encode(raw).decode("ascii")}
    return fixtures


def build() -> str:
    catalog = load_catalog()
    lesson_map = {part.num: load_lessons(part) for part in catalog}
    problems = validate_card_ids([lesson for lessons in lesson_map.values() for lesson in lessons])
    if problems:
        raise ValueError("; ".join(problems))
    parts = []
    lesson_xp = 0
    for part in catalog:
        lessons = lesson_map[part.num]
        lesson_xp += sum(l.xp for l in lessons)
        parts.append(
            {
                "num": part.num,
                "slug": part.slug,
                "title": part.title,
                "lesson": part.lesson_file.read_text(encoding="utf-8") if part.lesson_file.exists() else "",
                "lessons": [
                    {
                        "id": l.id,
                        "num": l.num,
                        "slug": l.slug,
                        "title": l.title,
                        "xp": l.xp,
                        "cards": [
                            {
                                "id": c.id,
                                "kind": c.kind,
                                "body": c.body,
                                "options": c.options,
                                "correct": c.correct,
                                "answers": c.answers,
                                "explanation": c.explanation,
                                "exercise_id": c.exercise_id,
                                "starter": c.starter if c.kind == "code" else None,
                                "prompt": c.prompt if c.kind == "code" else None,
                                "solution": c.solution if c.kind == "code" else None,
                                "test_source": c.test_source() if c.kind == "code" else None,
                            }
                            for c in l.cards
                        ],
                    }
                    for l in lessons
                ],
                "exercises": [
                    {
                        "id": ex.id,
                        "num": ex.num,
                        "slug": ex.slug,
                        "dir": ex.dir.name,
                        "title": ex.title,
                        "kyu": ex.kyu,
                        "xp": ex.xp,
                        "tags": ex.tags,
                        "hints": ex.hints,
                        "time_limit_min": ex.time_limit_min,
                        "timeout_s": ex.timeout_s,
                        "description": ex.description(),
                        "stub": ex.exercise_file.read_text(encoding="utf-8"),
                        "tests": ex.test_file.read_text(encoding="utf-8"),
                        "solution": ex.solution_file.read_text(encoding="utf-8"),
                        "fixtures": read_fixtures(ex.dir),
                    }
                    for ex in part.exercises
                ],
            }
        )
    data = {
        "version": __version__,
        "total_xp": total_xp(catalog) + lesson_xp,
        "card_xp": CARD_XP,
        "legacy_card_layout": LEGACY_LAYOUT["layout"],
        "legacy_card_ids": LEGACY_CARD_IDS,
        "kyu_xp": KYU_XP,
        "ranks": RANKS,
        "badges": {k: list(v) for k, v in BADGES.items()},
        "harness": HARNESS.read_text(encoding="utf-8"),
        "parts": parts,
    }
    payload = json.dumps(data, ensure_ascii=False, separators=(",", ":"))
    return "// Generated by tools/build_web.py. Do not edit by hand.\nwindow.COURSE_DATA = " + payload + ";\n"


def main(argv: list) -> int:
    content = build()
    if "--check" in argv:
        if not OUT.exists() or OUT.read_text(encoding="utf-8") != content:
            print(f"{OUT.relative_to(ROOT)} is stale. Run: python tools/build_web.py")
            return 1
        print(f"{OUT.relative_to(ROOT)} is up to date")
        return 0
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(content, encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)} ({OUT.stat().st_size // 1024} KB)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
